"""Add description field to Video model

Revision ID: 12670018c144
Revises: 
Create Date: 2025-04-25 00:42:52.577988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12670018c144'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
